inventory/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

# Student URLS
	url(r'^students/$', views.student_index, name='student_index'),
	url(r'^students/(?P<student_id>[0-9]+)/$', views.student_show, name='student_show'),
	url(r'^students/edit/(?P<student_id>[0-9]+)/$', views.student_edit, name='student_edit'),
	url(r'^students/search/$', views.student_search, name='student_search'),
	url(r'^students/(?P<student_id>\w+)/assign/$', views.device_search, name='device_search'),
	url(r'^students/create/$', views.student_create, name='student_create'),


#Program URLS
	url(r'^programs/$', views.program_index, name='program_index'),
	url(r'^programs/(?P<pk>[0-9]+)$', views.program_show, name='program_show'),

# Devices URLs
	url(r'^devices/search/$', views.device_search, name='device_search'),
	url(r'^devices/(?P<pk>[0-9]+)/$', views.device_show, name='device_show'),
	url(r'^devices/(?P<pk>[0-9]+)/edit/$', views.device_edit, name='device_edit'),
	url(r'^devices/import/$', views.device_import_select, name='device_import_select'),
	url(r'^devices/import/(?P<group_id>[0-9]+)$', views.device_import, name='device_import'),
	url(r'^devices/assign/$', views.device_assign, name='device_assign'),



]

mactrac/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mactrac.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('inventory.urls', namespace="inventory")),
    url(r'^admin/', include(admin.site.urls)),

]

inventory/models.py
from django.db import models
from django.contrib import admin
from datetime import datetime

class Program(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name


class Student(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	STATUS_CHOICES = (
			('ACTIVE', 'Active'),
			('INACTIVE', 'Inactive')
		)
	status = models.CharField(max_length=10, choices = STATUS_CHOICES, blank=False, default='ACTIVE')
	SCHOOL_CHOICES = (
			('KHS', 'Keansburg High School'),
			('BMS', 'Bolger Middle School'),
			('CES', 'Caruso Elementary School'),
			('PMR', 'Port Monmouth Road Elementary'),
			('OOD', 'Out of District Students'),
			('PREG', 'Pre-Registration Students'),
			('INACT', 'Inactive Students'),
			('EARLY', 'Early Intervention'),
			('STVOC', 'State Facility and Full Time Vocational'),
			('SS', 'Summer School KHS')
		)
	school = models.CharField(max_length=6, choices=SCHOOL_CHOICES, blank=False, default='KHS')
	GENDER_CHOICES = (
			('F','Female'),
			('M','Male'),
		)
	gender = models.CharField(max_length = 2, choices = GENDER_CHOICES, blank=False, default='F')

	@property
	def full_name(self):
		return self.first_name + " " + self.last_name
	student_id = models.CharField(max_length=50, blank=False, unique = True)
	state_id = models.CharField(max_length=50, blank=False, unique = True)
	GRADE_CHOICES = (
		('3H', 'Half-day Pre-School (3 Years Old)'),
		('3F', 'Full-day Pre-School (3 Years Old)'),
		('4H', 'Half-day Pre-School (4 Years Old)'),
		('4F', 'Full-day Pre-School (4 Years Old)'),
		('KH', 'Half-day Kindergarten'),
		('KF', 'Full-day Kindergarten'),
		('01', 'Grade 1'),
		('02', 'Grade 2'),
		('03', 'Grade 3'),
		('04', 'Grade 4'),
		('05', 'Grade 5'),
		('06', 'Grade 6'),
		('07', 'Grade 7'),
		('08', 'Grade 8'),
		('09', 'Grade 9'),
		('10', 'Grade 10'),
		('11', 'Grade 11'),
		('12', 'Grade 12'),
		('PG', 'Post Graduate'),
		('AD', 'Adult High School')
	)
	grade_level = models.CharField(max_length = 2, choices = GRADE_CHOICES, blank=False, default='12')
	program = models.ForeignKey('Program', blank=False, null=False, on_delete='SET_DEFAULT', default='1')

	def __unicode__(self):
		return self.full_name

class Status(models.Model):
	name = models.CharField(max_length=30)
	checkedout = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name



class Device(models.Model):
	name = models.CharField(max_length=50)
	serial_number = models.CharField(max_length=50)
	mac_address = models.CharField(max_length=50)
	model = models.CharField(max_length=100)

	status = models.ForeignKey('Status', blank=True, null=True, on_delete=models.SET_NULL)
	student = models.ForeignKey('Student', blank=True, null=True, on_delete=models.SET_NULL)
	program = models.ForeignKey('Program', blank=True, null=True, on_delete=models.SET_NULL)

	def __unicode__(self):
		return self.name

inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.core import serializers
import requests, json
import xml.etree.ElementTree as ET
from django.db.models import Q
from .models import Student
from django.shortcuts import get_object_or_404, redirect
from .forms import StudentForm

def index(request):
	return render(request, 'inventory/index.html')

def message(request):
	messages.error(request, "Exterminate!")
	messages.info(request, "Timey Wimey")
	messages.warning(request, "Why'd you go an do that!?")
	messages.success(request, "Alon Zi!")
	messages.debug(request, "The Doctor")
	return render(request, 'inventory/message.html')

def userSearchForm(request):
	return render(request, 'inventory/userSearchForm.html')

def showStudent(request, student_id):
	user = get_object_or_404(Student, student_id=student_id)
	return render(request, 'inventory/show.html', {'user': user})

def editStudent(request, student_id):
	student = get_object_or_404(Student, student_id=student_id)
	if request.method == "POST":
		form = StudentForm(request.POST, instance=student)
		if form.is_valid():
			student = form.save()
			return redirect('inventory:showStudent', student.student_id)
	form = StudentForm(instance=student)
	return render(request, 'inventory/editStudent.html', {'form':form, 'user': student})

def assignStudent(request, student_id):
	return HttpResponse('Student Assignment')

def studentSearch(request):

	query = request.POST.get('search', 0)
	if query == 0:
		return render(request, 'inventory/userSearchForm.html')
	else:
		results = Student.objects.all().filter(
			Q(first_name__icontains=query) |
			Q(last_name__icontains=query))
		if len(results) == 0:
			messages.error(request, "No Users Found!")
			return render(request, 'inventory/userSearchForm.html')
		else:
			return render(request, 'inventory/userSearchForm.html', {'data': results, 'query': query })

inventory/views/deployments.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from inventory.models import Student, Device, Status, Program
from django.shortcuts import get_object_or_404, redirect, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def program_index(request):
	program_list = Program.objects.all()
	unassigned_students = Student.objects.filter(program__isnull=True).count()
	unassigned_devices = Device.objects.filter(program__isnull=True).count()
	return render(request, 'inventory/program_index.html', {'program_list': program_list, 'unassigned_devices': unassigned_devices, 'unassigned_students': unassigned_students})

def program_show(request, pk):
	program = get_object_or_404(Program, pk=pk)
	student_list = program.student_set.all().order_by('grade_level', 'last_name', 'first_name')
	paginator = Paginator(student_list, 20)

	page = request.GET.get('page')
	try:
		students = paginator.page(page)
	except PageNotAnInteger:
		students = paginator.page(1)
	except EmptyPage:
		students = paginator.page(paginator.num_pages)

	return render_to_response('inventory/program_show.html', {'program': program, 'students': students})

inventory/views/devices.py
from inventory.models import *
from django.shortcuts import get_object_or_404, redirect, render_to_response, render
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse
from django.conf import settings
from inventory.forms import *
import requests, json

def device_search(request, student_id=0):
	devices = Device.objects.all()
	if student_id == 0:
		return render(request, 'inventory/device_search.html', { 'devices':devices })
	else:
		student = get_object_or_404(Student, student_id=student_id)
		return render(request, 'inventory/device_search.html', { 'devices':devices, 'student':student })

def device_edit(request, pk):
	device = get_object_or_404(Device, pk=pk)
	if request.method == "POST":
		form = DeviceEditForm(request.POST, instance=device)
		if form.is_valid():
			device = form.save()
			return redirect('inventory:device_show', device.pk)
	form = DeviceEditForm(instance=device)
	return render(request, 'inventory/device_edit.html', { 'form':form, 'device':device })

def device_assign(request):
	status_id = request.POST.get('device_status', 0)
	device_id = request.POST.get('device', 0)
	student_id = request.POST.get('student_id', 0)
	device = get_object_or_404(Device, pk=device_id)
	student = get_object_or_404(Student, student_id=student_id)
	if status_id != 0:
		status = get_object_or_404(Status, pk=status_id)
		device.status = status
	device.student = student
	device.save()

	return redirect('inventory:student_show', student_id=student.student_id)

def device_show(request, pk):
	device = get_object_or_404(Device, pk=pk)
	return render(request, 'inventory/device_show.html', {'device': device})

def device_print(request, pk):
	device = get_object_or_404(Device, pk=pk)
	return render(request, 'inventory/device_print.html', {'device': device})

def device_import_select(request):
	flag = 0
	data = 0
	if settings.JSS_URL == '':
		messages.error(request, "JSS URL not set!")
		flag = 1
	if settings.JSS_USER == '':
		messages.error(request, 'JSS User not set!')
		flag = 1
	if settings.JSS_PASSWORD == '':
		messages.error(request, 'JSS Password not set!')
		flag = 1
	if flag == 1:
		return render(request, 'inventory/device_import.html')
	else:
		url = settings.JSS_URL + "/advancedcomputersearches"
		headers = {'Accept':"application/json"}
		r = requests.get(url, headers = headers, auth=(settings.JSS_USER, settings.JSS_PASSWORD))
		if r.status_code == 200:
			data = r.json()
			data = data['advanced_computer_searches']
		else:
			messages.error(request, 'Error Retrieving Computer List! Status Code: ' + str(r.status_code))
		return render(request, 'inventory/device_import_select.html', {'data': data })


def device_import(request, group_id):
	flag = 0
	data = 0
	existsCount = 0
	importCount = 0
	if settings.JSS_URL == '':
		messages.error(request, "JSS URL not set!")
		flag = 1
	if settings.JSS_USER == '':
		messages.error(request, 'JSS User not set!')
		flag = 1
	if settings.JSS_PASSWORD == '':
		messages.error(request, 'JSS Password not set!')
		flag = 1
	if flag == 1:
		return render(request, 'inventory/device_import.html')
	else:
		url = settings.JSS_URL + "/advancedcomputersearches/id/" + group_id
		headers = {'Accept':"application/json"}
		r = requests.get(url, headers = headers, auth=(settings.JSS_USER, settings.JSS_PASSWORD))
		if r.status_code == 200:
			data = r.json()
			data = data['advanced_computer_search']['computers']
			for device in data:
				if Device.objects.filter(serial_number__iexact = device['Serial_Number']).exists():
					messages.info(request, "Device " + device['Computer_Name'] + " already exists")
					existsCount += 1
				else:
					d = Device(name = device['Computer_Name'], serial_number = device['Serial_Number'], mac_address = device['Wifi_Mac_Address'], model = device['Model'])
					d.save()
					messages.success(request, "Device " + device['Computer_Name'] + " imported sucessfully")
					importCount += 1
		else:
			messages.error(request, 'Error Retrieving Computer List! Status Code: ' + str(r.status_code))
		totalCount = importCount + existsCount
		return render(request, 'inventory/device_import_complete.html', { 'totalCount':totalCount, 'existsCount':existsCount, 'importCount':importCount })

inventory/views/students.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.core import serializers
import requests, json
import xml.etree.ElementTree as ET
from django.db.models import Q
from inventory.models import *
from django.shortcuts import get_object_or_404, redirect
from inventory.forms import *
from django.contrib.auth.decorators import login_required


def student_index(request):
	if request.method == "POST":
		form = StudentFilterForm(request.POST)
		grade = request.POST['grade_level']
		school = request.POST['school']
		program = request.POST['program']
		filtered_students = Student.objects.all()
		if grade != "ALL":
			filtered_students = filtered_students.filter(grade_level=grade)
		if school != "ALL":
			filtered_students = filtered_students.filter(school=school)
		if program != "":
			filtered_students = filtered_students.filter(program__id__exact=program)
		return render(request, 'inventory/student_index.html', {'students': filtered_students, 'form': form })
	else:
		students = Student.objects.all()
		form = StudentFilterForm()
		return render(request, 'inventory/student_index.html', {'students': students, 'form': form })

def student_show(request, student_id):
	user = get_object_or_404(Student, student_id=student_id)
	form = CheckOutForm()
	return render(request, 'inventory/student_show.html', {'user': user, 'form':form })

def student_create(request):
	title = "New Student"
	if request.method == "POST":
		form = StudentCreateForm(request.POST)
		if form.is_valid():
			student = form.save()
			return redirect('inventory:student_show', student.student_id)
		else:
			return render(request, 'inventory/student_edit.html', {'form':form, 'title':title })
	form = StudentCreateForm()
	return render(request, 'inventory/student_edit.html', {'form':form, 'title':title })

def student_edit(request, student_id):
	student = get_object_or_404(Student, student_id=student_id)
	if request.method == "POST":
		form = StudentEditForm(request.POST, instance=student)
		if form.is_valid():
			student = form.save()
			return redirect('inventory:student_show', student.student_id)
	form = StudentEditForm(instance=student)
	title = "Edit: " + student.full_name
	return render(request, 'inventory/student_edit.html', {'form':form, 'user': student, 'title':title })

def computerAssignSearch(request, student_id):
	student = get_object_or_404(Student, student_id=student_id)
	query = request.POST.get('search', 0)
	if query == 0:
		return render(request, 'inventory/computerAssignSearch.html', { 'student': student })
	else:
		query = "*" + query + "*"
		jss_url = "http://jss-client.keansburg.k12.nj.us:8080/JSSResource"
		headers = {'accept': 'application/json'}
		r = requests.get(jss_url + "/computers/match/" + query, auth=('checkin','checkin'), headers=headers)
		data = r.json()
		data = data['computers']
		if len(data) == 0:
			messages.error(request, "No Computers Found!")
			return render(request, 'inventry/compuerAssignSearch.html')
		else:
			return render(request, 'inventory/computerAssignSearch.html', {'data': data, 'query': query, 'student_id': student_id })


def student_search(request):

	query = request.POST.get('search', 0)
	program_id = request.POST.get('program', 0)
	grade_id = request.POST.get('grade', 0)
	programs = Program.objects.all()
	grades = Student._meta.get_field('grade_level').choices
	if query == 0:
		return render(request, 'inventory/student_search.html', {'grades': grades, 'programs': programs})
	else:
		results = Student.objects.all().filter(
			Q(first_name__icontains=query) |
			Q(last_name__icontains=query))
		if program_id != '':
			program = get_object_or_404(Program, pk=program_id)
			results = results.filter(program=program)
		if grade_id != '':
			results = results.filter(grade_level=grade_id)
		if len(results) == 0:
			messages.error(request, "No Users Found!")
			return render(request, 'inventory/student_search.html', {'grades': grades, 'programs': programs, 'program_id': program_id, 'grade_id': grade_id })
		else:
			return render(request, 'inventory/student_search.html', {'data': results, 'query': query, 'grades': grades, 'programs': programs, 'program_id': program_id, 'grade_id': grade_id })

inventory/templates/inventory/base.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Inventory</title>
        {% load staticfiles %}
          <link rel="icon" href="{% static 'inventory/favicon.ico' %}" />
        	<!-- Latest compiled and minified CSS -->
		      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

		      <!-- Optional theme -->
		      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
          <!-- DataTables CSS File -->
          <link rel="stylesheet" href="http://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css" />
          <!-- Datatables Responsive CSS -->
          <link rel="stylesheet" href="http://cdn.datatables.net/responsive/1.0.6/css/dataTables.responsive.css" />
          <!-- CSS File for Chosen Jquery Plugin -->
          <link rel="stylesheet" href="{% static 'inventory/chosen/chosen.min.css' %}" />
             <!-- Custom CSS File -->
          <link rel="stylesheet" href="{% static 'inventory/style.css' %}" />
    </head>

    <body>
    	<div class="container-fluid">
    	<nav class="navbar navbar-default navbar-fixed-top">
  			<div class="container-fluid">
   				<div class="navbar-header">
   					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation-bar">
        				<span class="sr-only">Toggle navigation</span>
       					<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
      				</button>
      				<a class="navbar-brand" href="{% url 'inventory:student_index' %}">
        				<img alt="Brand" width="17px" height="20px" src="http://www.keansburg.k12.nj.us/cms/lib02/NJ01001933/Centricity/Domain/777/New%20Titan%20KT.png">
      				</a>
    			</div>
    			<div class="collapse navbar-collapse" id="navigation-bar">
    				<ul class="nav navbar-nav">
    					<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Students <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'inventory:student_index' %}">All Students</a></li>
                  <li><a href="{% url 'inventory:student_create' %}">New Student</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Devices <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'inventory:device_search' %}">Device Search</a></li>
                  <li><a href="{% url 'inventory:device_import_select' %}">Import Devices</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Deployment <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'inventory:program_index' %}">Programs</a></li>
                  <li><a href="#">Reports</a></li>
                </ul>
              </li>
              <li>
                <a href="#">Setup</a>
    				</ul>
    			</div>
  			</div>
		</nav>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <p class="message-box {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}<p>
        {% endfor %}
      {% endif %}
    </div>
    	{% block content %}
    	{% endblock content %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <!-- Datatable jQuery Plugin -->
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.js"></script>
    <!-- Datatables BootStrap Inegration -->
    <script src="http://cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    <!-- Datatables responsive plugin -->
    <script src="http://cdn.datatables.net/responsive/1.0.6/js/dataTables.responsive.js"></script>
       <!-- Barcode Generator for print views -->
    <script src="{% static 'inventory/jquery-barcode.min.js' %}"></script>
    <!-- Chosen jQuery plugin -->
    <script src="{% static 'inventory/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'inventory/tables.js' %}"></script>
    </body>
</html>

inventory/templates/inventory/program_index.html
{% extends "inventory/base.html" %}

{% block content %}
<div class="container container-fluid">
	<h4>Program Index</h4>
	<table class="table table-striped">
		<tr>
			<th>Progam Name</th>
			<th>Assigned Students</th>
			<th>Assigned Devices</th>
		</tr>
		{% for program in program_list %}
		<tr>
			<td><a href="{% url 'inventory:program_show' program.id %}">{{ program.name }}</a></td>
			<td>{{ program.student_set.count }}</td>
			<td>{{ program.device_set.count }}</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock content %}

inventory/templates/inventory/student_index.html
{% extends "inventory/base.html" %}

{% block content %}
{% load widget_tweaks %}
<div class="container">
<h3>Student List</h3>
<p>Total Students: {{ students.count }}</p>
<div class="panel panel-default" id="studentFilterContainer">
	<div class="panel-heading">
		Filter by...
	</div>
	<div class="panel-body">
	<form method="post" action="{% url 'inventory:student_index' %}" class="form-inline">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group">
			<label class="control-label">{{ field.label }}</label>
			{{ field|add_class:"form-control" }}
		</div>
		{% endfor %}
		<div class="form-group">
			<button type="submit" class="save btn btn-primary form-control">Go</button>
		</div>
	</form>
</div>
</div>

	<table class="table table-striped display no-wrap" width="100%">
		<thead>
			<tr>
				<th class="mobile tablet desktop">Student Name</th>
				<th class="tablet desktop">Grade</th>
				<th class="tablet desktop">Gender</th>
				<th class="tablet desktop">School</th>
				<th class="tablet desktop">Program</th>
				<th class="tablet desktop">Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for student in students %}
				<tr {% if student.status == 'INACTIVE' %} class="danger" {% endif %}>
					<td><a href="{% url 'inventory:student_show' student.student_id %}" class="">{{ student.full_name }}</a></td>
					<td>{{ student.get_grade_level_display }}</td>
					<td>{{ student.get_gender_display }}</td>
					<td>{{ student.get_school_display }}</td>
					<td>{{ student.program }}</td>
					<td><a href="/students/{{ student.student_id }}/assign/" class="btn btn-xs btn-primary">{% if student.device_set.count == 0 %}Check Out Device{% else %}Check In Device{% endif %}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock content %}

inventory/templates/inventory/student_show.html
{% extends "inventory/base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
<div class="panel panel-default">
	<div class="panel-heading"><h4>{{ user.full_name }}</h4></div>
	<div class="panel-body">
	<div class="container-fluid">
		<div class="row">
		<div class="col-md-6">
			<dl class="dl-horizontal">
				<dt>Student ID</dt>
				<dd>{{ user.student_id }}</dd>
				<dt>State ID</dt>
				<dd>{{ user.state_id }}</dd>
				<dt>Status</dt>
				<dd>{{ user.get_status_display }}</dd>
			</dl>
		</div>
		<div class="col-md-6">
			<dl class="dl-horizontal">
				<dt>School</dt>
				<dd>{{ user.get_school_display }}</dd>
				<dt>Grade Level</dt>
				<dd>{{ user.get_grade_level_display }}</dd>
				<dt>Gender</dt>
				<dd>{{ user.get_gender_display }}</dd>
				<dt>Program</dt>
				<dd>{{ user.program.name }}</dd>
			</dl>
		</div>
	</div>
	<div class="row">
		{% if user.device_set.count > 0 %}
		<div class="col-lg">
			<h4>Assigned Devices</h4>
			<div class="table-responsive">
			<table class="table table-striped">
				<tr>
					<th>Device Name</th>
					<th>Serial Number</th>
					<th>MAC Address</th>
					<th>Status</th>
					<th>Actions</th>
				</tr>
				{% for device in user.device_set.all %}
					<tr>
						<td><a href="{% url 'inventory:device_show' device.id %}">{{ device.name }}</a></td>
						<td>{{ device.serial_number }}</td>
						<td>{{ device.mac_address }}</td>
						<td>{{ device.status }}</td>
						<td>
							<div class="btn-group btn-group-sm" role="group">
								<a href="#" class="btn btn-default" tabindex="-1">{% if device.status.checkedout == True %}Check In{% else %}Change Status{% endif %}</a>
								<a href="#" class="btn btn-default" tabindex="-1">Check Out</a>
								<a href="#" class="btn btn-default" tabindex="-1" alt="Print Device Label"><span class="glyphicon glyphicon-print"></span></a>
							</div>
						</td>
					</tr>
				{% endfor %}
			</table>
			</div>
		</div>
		{% else %}
		<div class="col-lg">	
			<h4>No Devices Assigned</h4>
		</div>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-lg">
			<div class="btn-group" role="group" aria-label="...">
				<a type="button" class="btn btn-default" href="{% url 'inventory:student_edit' user.student_id %}">Edit Student</a>
				<button type="button" class="btn btn-default" data-toggle="modal" data-target=".assign-device">Assign New Device</button>
				<a type="button" class="btn btn-default" href="{% url 'inventory:student_index' %}">Back to Search</a>

			</div>
		</div>
	</div>
	</div>
</div>
</div>
</div>
<div class="modal fade assign-device" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Assign New Device to {{ user.full_name }}</h4>
			</div>
			<div class="modal-body">
				<form method="post" action="{% url 'inventory:device_assign' %}" class="forms">
					{% csrf_token %}
					<input type="hidden" name="student_id" value="{{ user.student_id }}">
					{% for field in form %}
					<div class="form-group">
						<label class="control-label">{{ field.label }}</label>
						{{ field|add_class:"form-control chosen" }}
					</div>
					{% endfor %}
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       			<button type="button" class="btn btn-primary" id="form-submit">Save</button>
			</div>
		</div>
	</div>
</div>
{% endblock content %}